### ISSUE TITLE
AutoComplete and Arguments info

### ISSUE THREAD

**Issue by TopFuel** [Ahmad45123/ExtremePAWN#2]
I want to know if it is possible for you to add these two features:
![feature1](https://cloud.githubusercontent.com/assets/3332131/4038717/fff5518c-2cba-11e4-898d-f24f67e4efb2.jpg)

![feature2](https://cloud.githubusercontent.com/assets/3332131/4038718/0717772e-2cbb-11e4-8b32-e0903da353a2.jpg)

**Comment by Ahmad45123** [comment]
Actually I am working on a better thing.
The update will be up soon.

**Comment by TopFuel** [comment]
Ok thanks.

**Comment by Ahmad45123** [comment]
Done :+1: 
http://forum.sa-mp.com/showthread.php?t=532630&page=6
