### ISSUE TITLE
Bugs and suggestions.

### ISSUE THREAD

**Issue by TopFuel** [Ahmad45123/ExtremePAWN#3]
Hi thanks for adding the functionality that I had suggested before, so now I have a few bugs that I found and two suggestions.

Suggestions:
Change the default font for the same used in Pawno, the Courier New size 10.
And also if you can add other functionality that I had suggested, that when you open the parentheses in a function a pop-up appears showing which are the parameters of the function.

Bugs:
1: In the Object Explorer window when I click one of the options it is not going to the correct line.

2: In the Dialog Creator button when I leave the mouse over the button "ToolStripButton18" appears.

3: I do not know if it's a bug or it is not implemented yet but when an error or warning appears it can not go up to the line by clicking on the error or warning.

This are the bugs I found so far, apart from that the editor is very good.

Sorry for my bad English :).

Thanks.

**Comment by Ahmad45123** [comment]
When you choose something from the list, Its format appears in the the bottom of the screen Like this : http://gyazo.com/af9e5fd48a9fad09a726fb6a7413258e

Would you like the pop up thing ?

---

Bugs :
1) It actually doesn't go to the line, But it brings the function/stock in front of you in the visible place, Try it again...

2) Will be fixed.

3) Its not implemented, Good suggestion though.

**Comment by TopFuel** [comment]
I would like the pop-up, if you want you can put as an option in the settings, so if someone does not like the pop-up it can be disabled.

![popup](https://cloud.githubusercontent.com/assets/3332131/4064982/adc6145c-2e16-11e4-8463-5c87a13b3505.gif)

1) Yes I saw that he goes to a line near the function/stock, but if possible it would be nice to go to the line where function/stock begins, but it is working.

Thanks.

**Comment by Ahmad45123** [comment]
Everything done except the pop-up, Its still under development.
